### PR TITLE
Updated permission-based linking

### PR DESCRIPTION
**Pull request by thejoshtaylor**
It's better now, I swear

### CODE REVIEW

**Comment by thejoshtaylor** [comment]
It's official, I'm not cooperative

**Comment by natecarman** [comment]
Josh, the previous comment was very nice

**Comment by natecarman** [comment]
Ask Nicely next time please

**Comment by thejoshtaylor** [comment]
> Josh, the previous comment was not rude.

I HATE YOU!!!! ABUSE! ABUSE!

**Comment by Ajzboss** [comment]
Must be github acting weird

**Review by natecarman — APPROVED** [review]

**Pull request merged**
